#---------------------------------------------------------------------------------------------------------------------
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           *
#                                                                                                                    *
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    *
#  with the License. A copy of the License is located at                                                             *
#                                                                                                                    *
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    *
#                                                                                                                    *
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES *
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    *
#  and limitations under the License.                                                                                *
#---------------------------------------------------------------------------------------------------------------------
aws:
  accountId: AWS_ACCOUNTID
  region: AWS_REGION
  iot: 
    endpoint: FACADE_AWS_IOT_ENDPOINT

assetLibrary:
  apiFunctionName: FACADE_ASSETLIBRARY_APIFUNCTIONNAME
  mode: lambda

provisioning:
  apiFunctionName: FACADE_PROVISIONING_APIFUNCTIONNAME
  mode: lambda

commands:
  apiFunctionName: FACADE_COMMANDS_APIFUNCTIONNAME
  mode: lambda

mqtt:
  topics:
    activate:
      success: FACADE_MQTT_TOPICS_ACTIVATE_SUCCESS
      failure: FACADE_MQTT_TOPICS_ACTIVATE_FAILURE

paths:
  vehicles: FACADE_PATHS_VEHICLES
  users: FACADE_PATHS_USERS

templates:
  vehicle: FACADE_TEMPLATES_VEHICLE
  ecu: FACADE_TEMPLATES_ECU
  user: FACADE_TEMPLATES_USER
  supplier: FACADE_TEMPLATES_SUPPLIER

cors:
  origin: FACADE_CORS_ORIGIN

logging:
  level: FACADE_LOGGING_LEVEL
