#---------------------------------------------------------------------------------------------------------------------
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.                                           *
#                                                                                                                    *
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    *
#  with the License. A copy of the License is located at                                                             *
#                                                                                                                    *
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    *
#                                                                                                                    *
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES *
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    *
#  and limitations under the License.                                                                                *
#---------------------------------------------------------------------------------------------------------------------
aws:
  region: AWS_REGION

  s3:
    bucket: CDF_DATAGENERATION_AWS_S3_BUCKET

paths:
  suppliers:
    parent: CDF_DATAGENERATION_PATHS_SUPPLIERS_PARENT

certificateId: CDF_DATAGENERATION_CERTIFICATEID

logging:
  level: CDF_DATAGENERATION_LOGGING
