AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CMS - Post Deployment Insfratructure Configuration

Mappings:
  SourceCode:
    General:
      S3Bucket: ""
      KeyPrefix: ""

Parameters:

  CDFAssetLibraryFunctionName:
    Description: AssetLibrary REST API function name
    Type: String

  CDFCommandsFunctionName:
    Description: Commands REST API function name
    Type: String

  Environment:
    Description:  Name of environment.  Used to name the created resources.
    Type: String
    MinLength: 1

Resources:

  CustomResourceLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../packages/cdf-clients/core/deployment-helper/bundle.zip
      Handler: packages/cdf-clients/core/deployment-helper/dist/lambda_custom_resource_proxy.handler
      MemorySize: 512
      Role: !GetAtt CustomResourceLambdaRole.Arn
      Runtime: nodejs12.x
      Timeout: 60
      Tracing: Active
      Environment:
          Variables:
            NODE_CONFIG_DIR: 'packages/cdf-clients/core/deployment-helper/dist/config'

  CustomResourceLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'CDF Core application configuration override'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        # TODO: fix full access permission
        - arn:aws:iam::aws:policy/AWSIoTFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref CustomResourceLambdaPolicies

  CustomResourceLambdaPolicies:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'cdf-auto-infrastructure application policies'
      Path: "/cdf/cdf-auto-infrastructure/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "lambda:InvokeFunction"
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CDFAssetLibraryFunctionName}'
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CDFCommandsFunctionName}'

  # Create Vehicle assetlibrary Template
  AssetLibraryAutoVehicleTemplate:
    Type: Custom::AssetLibraryTemplate
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      Category: group
      TemplateId: auto_vehicle
      Body: |
        {
          "properties": {
            "make": {
              "type": "string"
            },
            "model": {
              "type": "string"
            },
            "modelYear": {
              "type": "integer"
            },
            "marketCode": {
              "type": [
                "string",
                "null"
              ],
              "enum": [
                "EUR",
                "NA",
                "CN"
              ]
            },
            "countryCode": {
              "type": [
                "string",
                "null"
              ],
              "enum": [
                "DE",
                "FR",
                "CN",
                "GB",
                "US"
              ]
            },
            "bodyType": {
              "type": "string",
              "enum": [
                "Saloon",
                "Estate",
                "SUV",
                "Coupe"
              ]
            },
            "fuelType": {
              "type": "string",
              "enum": [
                "Gas",
                "Diesel",
                "EV",
                "Hybrid_MHEV",
                "Hybrid_PHEV"
              ]
            },
            "transmissionType": {
              "type": "string",
              "enum": [
                "Manual",
                "Auto",
                "EV"
              ]
            },
            "transmissionAutoType": {
              "type": [
                "string",
                "null"
              ],
              "enum": [
                "7-speed",
                "8-speed",
                "9-speed"
              ]
            },
            "transmissionManualType": {
              "type": [
                "string",
                "null"
              ],
              "enum": [
                "5-speed",
                "6-speed"
              ]
            },
            "colorCode": {
              "type": [
                "string"
              ]
            },
            "iviType": {
              "type": [
                "string",
                "null"
              ],
              "enum": [
                "LoLine",
                "HiLine",
                "Premium"
              ]
            },
            "dtc": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "make",
            "model",
            "modelYear",
            "bodyType",
            "fuelType",
            "transmissionType",
            "colorCode",
            "iviType"
          ]
        }


    DependsOn:
      - AssetLibraryAutoSupplierTemplate

  # Create Supplier assetlibrary Template
  AssetLibraryAutoSupplierTemplate:
    Type: Custom::AssetLibraryTemplate
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      Category: group
      TemplateId: auto_supplier
      Body: |
        {
          "properties": {
            "externalId": {
              "type": "string"
            }
          },
          "required": []
        }



  # Create User assetlibrary Template
  AssetLibraryAutoUserTemplate:
    Type: Custom::AssetLibraryTemplate
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      Category: group
      TemplateId: auto_user
      Body: |
        {
          "properties": {
            "firstName": {
              "type": "string"
            },
            "lastName": {
              "type": "string"
            },
            "email": {
              "type": [
                "string",
                "null"
              ],
              "format": "email"
            },
            "addressLine1": {
              "type": "string"
            },
            "addressLine2": {
              "type": [
                "string",
                "null"
              ]
            },
            "city": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "country": {
              "type": "string"
            },
            "phone": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "relations": {
            "out": {
              "owns": [
                "auto_vehicle"
              ],
              "owned": [
                "auto_vehicle"
              ]
            }
          },
          "required": [
            "firstName",
            "lastName"
          ]
        }


    DependsOn:
      - AssetLibraryAutoVehicleTemplate
  # Create ECU assetlibrary Template
  AssetLibraryAutoEcuTemplate:
    Type: Custom::AssetLibraryTemplate
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      Category: device
      TemplateId: auto_ecu
      Body: |
        {
          "properties": {
            "softwareVersion": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "whitelisted",
                "assembled",
                "installed",
                "owned"
              ]
            },
            "type": {
              "type": "string",
              "enum": [
                "tcu",
                "gateeay",
                "bcm"
              ]
            },
            "model": {
              "type": "string"
            }
          },
          "relations": {
            "out": {
              "manufactured_by": [
                "auto_supplier"
              ],
              "installed_in": [
                "auto_vehicle"
              ]
            }
          },
          "required": []
        }

    DependsOn:
      - AssetLibraryAutoVehicleTemplate
      - AssetLibraryAutoSupplierTemplate
  # Create assetlibrary Groups structure
  AssetLibraryTestDataBulkGroups:
    Type: Custom::AssetLibraryBulkGroups
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      Body: |
        {
          "groups": [
            {
              "templateId": "root",
              "parentPath": "/",
              "name": "Auto",
              "attributes": {}
            },
            {
              "templateId": "root",
              "parentPath": "/auto",
              "name": "suppliers",
              "attributes": {}
            },
            {
              "templateId": "root",
              "parentPath": "/auto/suppliers",
              "name": "Acme Electronics",
              "attributes": {}
            },
            {
              "templateId": "root",
              "parentPath": "/auto",
              "name": "vehicles",
              "attributes": {}
            },
            {
              "templateId": "root",
              "parentPath": "/auto",
              "name": "users",
              "attributes": {}
            }
          ]
        }



    DependsOn:
      - AssetLibraryAutoUserTemplate
      - AssetLibraryAutoEcuTemplate
      - AssetLibraryAutoVehicleTemplate
      - AssetLibraryAutoSupplierTemplate

  # Create Assetlibrary provisioning template
  AssetLibraryDemoProvisioningTemplate:
    Type: Custom::AssetLibraryPolicy
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFAssetLibraryFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      PolicyId: TCUProvisioningTemplate
      Body: |
        {
          "policyId": "TCUProvisioningTemplate",
          "type": "ProvisioningTemplate",
          "description": "TCU provisioning template",
          "appliesTo": [
            "/auto/suppliers"
          ],
          "document": "{\"template\":\"tcu\"}"
        }
    DependsOn:
      - AssetLibraryTestDataBulkGroups

  # Create OTA Job Command template
  OtaJobTemplate:
    Type: Custom::CommandsTemplate
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt CustomResourceLambda.Arn
      FunctionName: !Ref CDFCommandsFunctionName
      ContentType: application/vnd.aws-cdf-v1.0+json
      TemplateId: OtaUpdate
      Body: |
        {
          "templateId": "OtaUpdate",
          "operation" : "OtaUpdate",
          "description": "A template used for rolling out OS updates",
          "document": "{\"operation\":\"OtaUpdate\", \"desiredVersion\":\"${cdf:parameter:desiredVersion}\"}",
          "requiredDocumentParameters": [
            "desiredVersion"
          ],
          "presignedUrlExpiresInSeconds": 3600
        }
